apiVersion: v1
kind: Namespace
metadata:
  name: lattice
  labels:
    # Pod Security Admission: reject any pod in this namespace that isn't fully restricted.
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
