package com.lattice.oidc.handlers;

import com.authlete.common.api.AuthleteApi;
import com.authlete.common.dto.BackchannelAuthenticationCompleteRequest.Result;
import com.authlete.common.dto.BackchannelAuthenticationCompleteRequest;
import com.authlete.common.dto.BackchannelAuthenticationCompleteResponse;
import com.authlete.common.dto.BackchannelAuthenticationFailRequest.Reason;
import com.authlete.common.dto.BackchannelAuthenticationFailRequest;
import com.authlete.common.dto.BackchannelAuthenticationFailResponse;
import com.authlete.common.dto.BackchannelAuthenticationIssueRequest;
import com.authlete.common.dto.BackchannelAuthenticationIssueResponse;
import com.authlete.common.dto.BackchannelAuthenticationResponse;
import com.authlete.common.dto.Scope;
import com.lattice.oidc.client.AuthleteExecutionContext;
import com.lattice.oidc.common.Caches;
import com.lattice.oidc.common.LatticeConfig;
import com.lattice.oidc.common.Responses;
import com.lattice.oidc.common.WebException;
import com.lattice.oidc.models.User;
import com.lattice.oidc.stores.UserStore;
import java.time.Duration;
import java.util.Arrays;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;
import javax.inject.Inject;
import javax.inject.Provider;
import javax.inject.Singleton;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import play.cache.NamedCache;
import play.cache.SyncCacheApi;
import play.libs.ws.WSClient;
import play.libs.ws.WSResponse;

/**
 * Drives the end-user's decision on the authentication device and reports it to Authlete
 * (/backchannel/authentication/complete), delivering ping/push notifications to the client.
 */
@Singleton
public final class CibaHandler {

  private static final Logger LOG = LoggerFactory.getLogger(CibaHandler.class);

  /** What is needed to complete a pending CIBA request. */
  public record Pending(String ticket, String subject, String[] claimNames, String[] acrs) {}

  private final Provider<AuthleteApi> api;
  private final AuthenticationDevice device;
  private final UserStore users;
  private final SyncCacheApi cache;
  private final WSClient ws;
  private final AuthleteExecutionContext executionContext;
  private final LatticeConfig config;

  @Inject
  public CibaHandler(
      Provider<AuthleteApi> api,
      AuthenticationDevice device,
      UserStore users,
      @NamedCache(Caches.CIBA) SyncCacheApi cache,
      WSClient ws,
      AuthleteExecutionContext executionContext,
      LatticeConfig config) {
    this.api = api;
    this.device = device;
    this.users = users;
    this.cache = cache;
    this.ws = ws;
    this.executionContext = executionContext;
    this.config = config;
  }

  /**
   * Identifies the end-user, validates the request further, issues an {@code auth_req_id} and starts
   * communicating with the authentication device. Returns the response content for the client
   * (containing {@code auth_req_id}); failures are thrown as {@link WebException}s carrying the
   * error response generated by Authlete.
   */
  public String identifyAndIssue(BackchannelAuthenticationResponse backchannelResponse) {
    // Identify a user based on the hint contained in the backchannel authentication request. If no
    // user can be identified by the hint, the request fails with "unknown_user_id".
    User user = userByHint(backchannelResponse).orElseThrow(() -> fail(backchannelResponse.getTicket(), Reason.UNKNOWN_USER_ID));
    // Check the user code contained in the backchannel authentication request if necessary
    // (backchannel_user_code_parameter). The user code is stored as the "code" attribute of the user.
    if (backchannelResponse.isUserCodeRequired()) {
      Object code = user.getAttribute("code");
      if (!(code instanceof String c) || !c.equals(backchannelResponse.getUserCode())) {
        throw fail(backchannelResponse.getTicket(), Reason.INVALID_USER_CODE);
      }
    }
    // Check the binding message in the backchannel authentication request if necessary. It must be
    // short and printable because it is displayed on both the consumption and authentication devices.
    String bindingMessage = backchannelResponse.getBindingMessage();
    if (bindingMessage != null && (bindingMessage.length() > 128 || bindingMessage.chars().anyMatch(Character::isISOControl))) {
      throw fail(backchannelResponse.getTicket(), Reason.INVALID_BINDING_MESSAGE);
    }

    // Issue an 'auth_req_id' by calling Authlete's /api/backchannel/authentication/issue API.
    BackchannelAuthenticationIssueResponse issue =
        api.get().backchannelAuthenticationIssue(new BackchannelAuthenticationIssueRequest().setTicket(backchannelResponse.getTicket()));
    if (issue.getAction() != BackchannelAuthenticationIssueResponse.Action.OK) {
      // 500 Internal Server Error (INTERNAL_SERVER_ERROR, INVALID_TICKET)
      throw new WebException(Responses.serverError(issue.getResponseContent()));
    }
    // 200 OK. Start communicating with the authentication device for end-user authentication and
    // authorization (in the background).
    start(user, backchannelResponse, issue);
    return issue.getResponseContent();
  }

  /**
   * Gets a user by the hint. A {@code login_hint} may be a subject, an email address or a phone
   * number; for an {@code id_token_hint}, Authlete has already validated the ID token and extracted
   * its subject. {@code login_hint_token} formats are deployment-specific and none is supported, so
   * such requests fail with {@code unknown_user_id} (a deployment that adds one must also check its
   * expiry and fail with {@code expired_login_hint_token}).
   */
  private Optional<User> userByHint(BackchannelAuthenticationResponse backchannelResponse) {
    if (backchannelResponse.getHintType() == null) {
      return Optional.empty();
    }
    String hint = backchannelResponse.getHint();
    return switch (backchannelResponse.getHintType()) {
      case LOGIN_HINT ->
          users.bySubject(hint).or(() -> users.byEmail(hint)).or(() -> users.byPhoneNumber(hint));
      case ID_TOKEN_HINT -> users.bySubject(backchannelResponse.getSub());
      default -> Optional.empty();
    };
  }

  /**
   * Generates an error response by calling Authlete's /api/backchannel/authentication/fail API.
   */
  private WebException fail(String ticket, Reason reason) {
    BackchannelAuthenticationFailResponse r =
        api.get().backchannelAuthenticationFail(new BackchannelAuthenticationFailRequest().setTicket(ticket).setReason(reason));
    String content = r.getResponseContent();
    return new WebException(
        switch (r.getAction()) {
          case BAD_REQUEST -> Responses.badRequest(content);
          case FORBIDDEN -> Responses.forbidden(content, null);
          default -> Responses.serverError(content);
        });
  }

  /**
   * Starts communicating with the authentication device for end-user authentication and
   * authorization. Runs in the background so that the backchannel authentication response is
   * returned to the client immediately.
   *
   * <ul>
   *   <li>sync: wait for the end-user's decision on the device.
   *   <li>async: the device calls back {@code /api/backchannel/authentication/callback}.
   *   <li>poll: poll the device for the result.
   * </ul>
   */
  public void start(User user, BackchannelAuthenticationResponse backchannelResponse, BackchannelAuthenticationIssueResponse issue) {
    Pending pending = new Pending(backchannelResponse.getTicket(), user.getSubject(), backchannelResponse.getClaimNames(), backchannelResponse.getAcrs());
    String message = message(backchannelResponse);
    int timeout = authTimeout(issue.getExpiresIn());
    String authReqId = issue.getAuthReqId();
    CompletableFuture.runAsync(
        () -> {
          try {
            switch (config.ciba().mode()) {
              case SYNC -> complete(pending, device.sync(user.getSubject(), message, timeout, authReqId));
              case ASYNC -> {
                String requestId = device.async(user.getSubject(), message, timeout, authReqId);
                cache.set(key(requestId), pending, Math.max(issue.getExpiresIn(), 60));
              }
              case POLL -> poll(pending, device.poll(user.getSubject(), message, timeout, authReqId));
            }
          } catch (RuntimeException e) {
            LOG.warn("CIBA authentication device interaction failed: {}", e.getMessage());
            fail(pending, Result.TRANSACTION_FAILED, "Communication with the authentication device failed.");
          }
        },
        executionContext.current());
  }

  /** Handles the device's asynchronous callback. Returns false for unknown request ids. */
  public boolean callback(String requestId, AuthenticationDevice.Outcome outcome) {
    Optional<Pending> pending = cache.get(key(requestId));
    if (pending.isEmpty()) {
      return false;
    }
    cache.remove(key(requestId));
    complete(pending.get(), outcome);
    return true;
  }

  private void poll(Pending pending, String requestId) {
    Duration interval = config.ciba().pollInterval();
    for (int i = 1; i <= config.ciba().pollMaxCount(); i++) {
      AuthenticationDevice.Outcome outcome = device.result(requestId);
      if (outcome != null) {
        complete(pending, outcome);
        return;
      }
      try {
        TimeUnit.MILLISECONDS.sleep(interval.toMillis());
      } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
        break;
      }
    }
    fail(pending, Result.TRANSACTION_FAILED, "The end-user did not respond in time.");
  }

  /**
   * Completes the process with the result of end-user authentication and authorization, by calling
   * Authlete's /api/backchannel/authentication/complete API.
   */
  private void complete(Pending pending, AuthenticationDevice.Outcome outcome) {
    switch (outcome) {
      case ALLOW -> authorize(pending);
      case DENY -> fail(pending, Result.ACCESS_DENIED, "The end-user denied the request.");
      case TIMEOUT -> fail(pending, Result.TRANSACTION_FAILED, "The authentication device timed out.");
      default -> fail(pending, Result.TRANSACTION_FAILED, "Unrecognized result from the authentication device.");
    }
  }

  private void authorize(Pending pending) {
    Optional<User> user = users.bySubject(pending.subject());
    if (user.isEmpty()) {
      fail(pending, Result.TRANSACTION_FAILED, "The user no longer exists.");
      return;
    }
    // OK. The end-user has successfully authorized the client. Complete the process with the
    // authentication time, the acr value that was actually used and the user's claims.
    BackchannelAuthenticationCompleteRequest request =
        new BackchannelAuthenticationCompleteRequest()
            .setTicket(pending.ticket())
            .setSubject(pending.subject())
            .setResult(Result.AUTHORIZED)
            .setAuthTime(System.currentTimeMillis() / 1000L)
            .setAcr(acr(pending.acrs()));
    Map<String, Object> claims = new ClaimsCollector(user.get()).collect(pending.claimNames(), null);
    if (claims != null) {
      request.setClaims(claims);
    }
    send(request);
  }

  /**
   * The end-user authorization has not been successfully done. Complete the process with failure
   * (access_denied or transaction_failed, with an error description).
   */
  private void fail(Pending pending, Result result, String description) {
    send(
        new BackchannelAuthenticationCompleteRequest()
            .setTicket(pending.ticket())
            .setSubject(pending.subject())
            .setResult(result)
            .setErrorDescription(description));
  }

  private void send(BackchannelAuthenticationCompleteRequest request) {
    BackchannelAuthenticationCompleteResponse response =
        api.get().backchannelAuthenticationComplete(request);
    // 'action' in the response denotes the next action which
    // this service implementation should take.
    switch (response.getAction()) {
      // Send a notification to the client. This happens when the backchannel token delivery mode is
      // "ping" or "push".
      case NOTIFICATION -> notifyClient(response);
      // No action is required. This happens when the backchannel token delivery mode is "poll".
      case NO_ACTION -> {}
      // Server error.
      default -> LOG.error("CIBA completion failed: {}", response.getResultMessage());
    }
  }

  /** Ping/push mode: POST the result to the client notification endpoint (no redirects). */
  private void notifyClient(BackchannelAuthenticationCompleteResponse response) {
    if (response.getClientNotificationEndpoint() == null) {
      return;
    }
    Duration timeout = config.ciba().notificationTimeout();
    try {
      WSResponse r =
          ws.url(response.getClientNotificationEndpoint().toString())
              .setFollowRedirects(false)
              .setRequestTimeout(timeout)
              .addHeader("Authorization", "Bearer " + response.getClientNotificationToken())
              .setContentType("application/json")
              .post(response.getResponseContent())
              .toCompletableFuture()
              .get(timeout.toMillis() + 1_000L, TimeUnit.MILLISECONDS);
      if (r.getStatus() / 100 != 2 && r.getStatus() / 100 != 3) {
        LOG.warn("CIBA client notification returned HTTP {}", r.getStatus());
      }
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    } catch (Exception e) {
      LOG.warn("CIBA client notification failed: {}", e.getMessage());
    }
  }

  private String acr(String[] requested) {
    if (requested == null) {
      return null;
    }
    return Arrays.stream(requested).filter(config.satisfiedAcrs()::contains).findFirst().orElse(null);
  }

  private int authTimeout(int expiresIn) {
    int t = (int) (config.ciba().authTimeoutRatio() * expiresIn);
    return Math.max(AuthenticationDevice.AUTH_TIMEOUT_MIN, Math.min(AuthenticationDevice.AUTH_TIMEOUT_MAX, t));
  }

  private static String message(BackchannelAuthenticationResponse backchannelResponse) {
    StringBuilder sb =
        new StringBuilder("Client App (")
            .append(backchannelResponse.getClientName())
            .append(") is requesting the following permissions.");
    Scope[] scopes = backchannelResponse.getScopes();
    if (scopes != null && scopes.length > 0) {
      sb.append(" [Requested scopes]: ")
          .append(Arrays.stream(scopes).map(Scope::getName).collect(Collectors.joining(",")));
    }
    if (backchannelResponse.getBindingMessage() != null) {
      sb.append(" [Binding message]: ").append(backchannelResponse.getBindingMessage());
    }
    return sb.toString();
  }

  private static String key(String requestId) {
    return "ciba:" + requestId;
  }
}
