package com.lattice.oidc.handlers;

import com.authlete.common.api.AuthleteApi;
import com.authlete.common.dto.TokenCreateRequest;
import com.authlete.common.dto.TokenCreateResponse;
import com.authlete.common.dto.TokenResponse;
import com.authlete.common.types.GrantType;
import com.authlete.common.types.TokenType;
import com.lattice.oidc.client.ServerMetadata;
import com.lattice.oidc.security.JwtVerifier;
import com.nimbusds.jwt.JWTClaimsSet;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import jakarta.inject.Inject;
import jakarta.inject.Provider;
import jakarta.inject.Singleton;
import play.mvc.Result;

/**
 * Processing of the grants that Authlete parses but leaves to the authorization server: token
 * exchange (RFC 8693) and JWT authorization grants (RFC 7523). Both require an identifiable client
 * and a JWT whose signature this server has verified.
 *
 * <p>RFC 8693 is very flexible. In other words, the specification does not define details that are
 * necessary for secure token exchange, so implementations have to complement it with their own
 * rules. The rules here: the client must be identifiable; access/refresh tokens must have been
 * issued by this server (Authlete has validated them); JWT and ID token subject tokens must be
 * signed by this server or by a configured trusted issuer.
 *
 * <p>Likewise, RFC 7523 does not define how the assertion JWT is generated by whom, nor how to
 * obtain the key to verify its signature, so each deployment has to define its own rules. Note
 * that the authorization server must verify the signature of the assertion by itself: the JavaDoc
 * of {@code TokenResponse} explains which validation steps Authlete performs and why Authlete
 * cannot verify the signature. Here, assertions must be signed by this server or by a configured
 * trusted issuer, and their audience must identify this server.
 *
 * @see <a href="https://www.rfc-editor.org/rfc/rfc8693.html">RFC 8693 OAuth 2.0 Token Exchange</a>
 * @see <a href="https://www.rfc-editor.org/rfc/rfc7521.html">RFC 7521 Assertion Framework for OAuth 2.0 Client Authentication and Authorization Grants</a>
 * @see <a href="https://www.rfc-editor.org/rfc/rfc7523.html">RFC 7523 JSON Web Token (JWT) Profile for OAuth 2.0 Client Authentication and Authorization Grants</a>
 */
@Singleton
public final class TokenGrantHandler {

  private static final String ACCESS_TOKEN_TYPE = "urn:ietf:params:oauth:token-type:access_token";

  private final Provider<AuthleteApi> api;
  private final JwtVerifier verifier;
  private final ServerMetadata server;

  @Inject
  public TokenGrantHandler(Provider<AuthleteApi> api, JwtVerifier verifier, ServerMetadata server) {
    this.api = api;
    this.verifier = verifier;
    this.server = server;
  }

  /**
   * Processes a token exchange request: determines the subject from the subject token and creates
   * a new access token for it with Authlete's /api/auth/token/create API.
   */
  public Result tokenExchange(TokenResponse token, Map<String, String> headers) {
    // This authorization server does not allow unidentifiable clients to make token exchange
    // requests.
    long clientId = requireClient(token, headers);
    TokenType type = token.getSubjectTokenType();
    String subject =
        switch (type) {
          // Authlete has already validated tokens it issued itself.
          case ACCESS_TOKEN, REFRESH_TOKEN ->
              token.getSubjectTokenInfo() == null ? null : token.getSubjectTokenInfo().getSubject();
          // The subject is the "sub" claim of the JWT, which must be signed (not encrypted) by a trusted
          // issuer.
          case JWT, ID_TOKEN -> verifiedSubject(token.getSubjectToken(), null, headers, "invalid_request");
          // SAML 1.1 / SAML 2.0 assertions and other token types are not supported.
          default ->
              throw TokenResponses.error(
                  400, "invalid_request", "Unsupported subject_token_type: " + type, headers);
        };
    if (subject == null) {
      throw TokenResponses.error(
          400, "invalid_request", "The subject could not be determined from the subject token.", headers);
    }
    TokenCreateResponse created =
        create(
            new TokenCreateRequest()
                .setGrantType(GrantType.TOKEN_EXCHANGE)
                .setClientId(clientId)
                .setScopes(token.getScopes())
                .setResources(token.getResources())
                .setSubject(subject),
            headers);
    return TokenResponses.success(created, ACCESS_TOKEN_TYPE, headers);
  }

  /**
   * Processes a token request using the grant type {@code
   * urn:ietf:params:oauth:grant-type:jwt-bearer}: verifies the assertion and creates an access token
   * for its subject with Authlete's /api/auth/token/create API.
   */
  public Result jwtBearer(TokenResponse token, Map<String, String> headers) {
    long clientId = requireClient(token, headers);
    // RFC 7523 §3: the assertion's audience must identify this authorization server.
    Set<String> audiences = new HashSet<>();
    audiences.add(server.issuer());
    Object tokenEndpoint = server.get("token_endpoint");
    if (tokenEndpoint != null) {
      audiences.add(tokenEndpoint.toString());
    }
    String subject = verifiedSubject(token.getAssertion(), audiences, headers, "invalid_grant");
    TokenCreateResponse created =
        create(
            new TokenCreateRequest()
                .setGrantType(GrantType.JWT_BEARER)
                .setClientId(clientId)
                .setScopes(token.getScopes())
                .setSubject(subject),
            headers);
    return TokenResponses.success(created, null, headers);
  }

  private String verifiedSubject(
      String jwt, Set<String> audiences, Map<String, String> headers, String error) {
    try {
      JWTClaimsSet claims = verifier.verify(jwt, audiences, false);
      return claims.getSubject();
    } catch (JwtVerifier.InvalidJwtException e) {
      throw TokenResponses.error(400, error, e.getMessage(), headers);
    }
  }

  private static long requireClient(TokenResponse token, Map<String, String> headers) {
    if (token.getClientId() == 0) {
      throw TokenResponses.error(
          400, "invalid_request", "This grant requires an identifiable client.", headers);
    }
    return token.getClientId();
  }

  private TokenCreateResponse create(TokenCreateRequest request, Map<String, String> headers) {
    TokenCreateResponse response = api.get().tokenCreate(request);
    if (response.getAction() != TokenCreateResponse.Action.OK) {
      throw TokenResponses.error(500, "server_error", "Token creation failed.", headers);
    }
    return response;
  }
}
